# Generated by Django 5.1.1 on 2024-09-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asignaturas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asignatura", models.CharField(max_length=500)),
                ("semestre", models.IntegerField()),
                ("creditos", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="apuntes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_tema", models.CharField(max_length=1000)),
                ("dir", models.FileField(upload_to="apuntes/")),
                (
                    "asignatura",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apuntes.asignaturas",
                    ),
                ),
            ],
        ),
    ]
