# Generated by Django 5.1.1 on 2024-09-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0002_asignaturas_apuntes_asi_asignat_ee1037_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apuntes",
            name="dir",
            field=models.FileField(upload_to="apuntes/documents/"),
        ),
    ]
